### PR TITLE
Enable SSL Authentication for Medusa to access Cassandra SSL Clusters

### PR DESCRIPTION
**Pull request by SINDHUJA21**

### CODE REVIEW

**Comment by adejanovski** [comment]
Hi @SINDHUJA21,

this is a great addition to Medusa, thanks!
What we would need know is to add an integration test for this, so that we can prevent our future selves from regressions. 
We can assist you in writing those, but it should be mostly about [setting up the ccm clusters with SSL encryption](https://github.com/thelastpickle/cassandra-medusa/blob/master/.github/workflows/ci.yml), and [configuring integration tests appropriately](https://github.com/thelastpickle/cassandra-medusa/blob/master/tests/integration/features/steps/integration_steps.py#L136-L173). We could enable SSL only for tests with the local backend, so that we still have tests with no client encryption (S3 and GCS).
wdyt?

**Comment by SINDHUJA21** [comment]
Hi @adejanovski,

I have done the following  to access the Cassandra SSL cluster:

1. Enabled SSL Client authentication for medusa CLI to access the Cassandra SSL cluster.
2. Enabled SSL Client authentication for SSTableloader.
3. Altered integration test to test the aforementioned cases.

**Comment by adejanovski** [comment]
Awesome @SINDHUJA21 !

I successfully ran the integration tests with and without client encryption, and it worked fine.
There's some confusion around the ordering of commits and the fact that you merged master into your branch : 
Commits · SINDHUJA21 cassandra-medusa

Could you do the following please?

- Do an interactive rebase on your branch using: `git rebase -i HEAD~4`
- From this starting point: 
```
pick a6d3474 Enable SSL Authentication for Medusa to access Cassandra SSL Clusters
pick d550187 Update for linting failures
pick 454844c Update for linting failures
pick bc89c77 Add a delete-backup command
pick 2b63451 fix multiple issues: #86, #89, #90
pick 7c897cf Document limitations very visibly. Fixes #40
pick 8805a16 Local and s3 RGW backends now use streams for both uploads and downloads.
```

get to this:

```
pick bc89c77 Add a delete-backup command
pick 2b63451 fix multiple issues: #86, #89, #90
pick 7c897cf Document limitations very visibly. Fixes #40
pick 8805a16 Local and s3 RGW backends now use streams for both uploads and downloads.
pick a6d3474 Enable SSL Authentication for Medusa to access Cassandra SSL Clusters
squash d550187 Update for linting failures
squash 454844c Update for linting failures
```

It'll reorder the commits to put yours as a single squashed commit at the end.
You'll have to resolve conflicts twice in the process.

Then you should be able to refresh your master branch from the upstream master and do a final rebase of your branch on top of master.
Once you checked that all tests are still passing, you can force push your branch using `git push --force-with-lease`,  which will update the PR.
I can then merge it into `master`.

Let me know if you need assistance.

**Comment by adejanovski** [comment]
@SINDHUJA21, I've created #122 where I rebased your work on top of master. I just had to fix two conflicts on the README.md file.
As you can see it just contains a single commit, which is what we want to achieve (there are still commits in your PR that don't belong there and are due to the use of  `git merge master` I'd say).

We can :

- merge PR #122 (and you're still credited as the author as you can see [here](https://github.com/thelastpickle/cassandra-medusa/pull/122/commits) )
- or you can rebase your branch on top of master after rebasing your fork's master on top of the upstream master and force push again to see if that fixes it.

Let me know what you prefer.

**Comment by SINDHUJA21** [comment]
@adejanovski, I would prefer merging PR #122.

**Comment by adejanovski** [comment]
Sounds good @SINDHUJA21, I'll close this PR then and merge #122.

Thanks!

**Pull request closed without merging**
