### PR TITLE
Adding support for Env Credentials and IAM Role

### PR DESCRIPTION
**Pull request by alvaropalmeirao**
Adding support for OS Environment credentials and IAM Role credentials. Any problem/change please feel free to request changes.

### CODE REVIEW

**Comment by adejanovski** [comment]
Thanks @alvaropalmeirao!
I'll review this PR ASAP and run some tests.

**Comment by alvaropalmeirao** [comment]
Requirement added to setup.py and commits squashed.

**Comment by adejanovski** [comment]
All good, thanks!

**Comment by alvaropalmeirao** [comment]
Waiting for new release! :)

**Pull request merged**
