### PR TITLE
Added minio support

### PR DESCRIPTION
**Pull request by DrissiReda**
Solves #236

### CODE REVIEW

**Comment by burmanm** [comment]
I don't see the point in having ``ibm_cloud_storage/`` and ``minio_storage/`` directories with nearly similar files. I think all these S3-compatible storages should have a common directory and only override something if necessary. For example, these two directories have nearly no difference (one does self.endpoint_url formatting while other one does it later - but they could both use the self) other than the selection of region pointing to URL. 

Having less copies of the same functionality makes it easier to maintain these. There's plenty of S3 compatible clones and I guess we'd like to support all of them through some ``s3compat`` type of driver. That should be somewhat easy as we only use few features so the difference between say Minio and DigitalOcean's Spaces, B2 Backblaze, etc shouldn't make any difference to us. I'd say we probably don't even need to update the libcloud and use the minio driver from there, but perhaps just making the ibm_cloud_storage code to be generic s3compat would do the job (excluding the region autofilling). To me setting the endpoint url should be fine override to provide lowest possible work to connect to any provider. @adejanovski would you oppose such "quick fix" ? It would make testing easier as the docker compose or equal could spin up minio for testing the backups against s3 / awscli.

**Comment by DrissiReda** [comment]
Indeed if we could expose the endpoint url and the region in the configuration, it could work. Make the region be autofilled if the setting wasn't provided. Hardcoding the region will definitely break some otherwise compatible s3 backends.

**Comment by david316** [comment]
I thought that it might be relevant to let you know that I've successfully used the Ceph s3_rgw provider with Minio. 

I agree with the concept of a more generic s3 compatible provider that accepts an endpoint and region configuration.

**Comment by adejanovski** [comment]
> To me setting the endpoint url should be fine override to provide lowest possible work to connect to any provider. @adejanovski would you oppose such "quick fix" ? It would make testing easier as the docker compose or equal could spin up minio for testing the backups against s3 / awscli.

@burmanm, I'm happy with your suggestion. We already have a `host` setting that is used for the endpoint in the s3_rgw implementation and the region is available already as well. The IBM storage code seems fit as base for an `S3Generic`/`S3Compatible` class.

We will then also merge the `concurrent.py` and `awscli.py` variants into a single one by using the `ibm_cloud_storage` one and adapting it for the AWS S3 case (ie removing the `endpoint-url` and `region` arguments in the aws cli calls).

**Comment by adejanovski** [comment]
@DrissiReda, the newly merged support for S3 compatible implementations should provide Minio access.
Would you mind testing `master` with Minio and tell us if it works ok for you?
Seems like we've been unable to reproduce the region issue you've seen.
Thanks!

**Comment by adejanovski** [comment]
Closing this PR as MinIO support was merged to `master` through another PR.
Thanks a lot @DrissiReda for pushing this PR nonetheless!

**Pull request closed without merging**
