### PR TITLE
Keep system keyspaces when user specifies ks/tables

### LINKED ISSUE #136: system_schema ks is not restored when restoring select ks/tables
When a list of keyspaces and/or tables is set in the restore-cluster command, Medusa will not restore the `system_schema` ks.
This ends up not creating the underlying schema of the sstables we're restoring.

### PR DESCRIPTION
**Pull request by arodrime**
Fixes #136.

Tested and working specifying a keyspace or a table.

### CODE REVIEW

**Comment by arodrime** [comment]
When using sstable loader, we don't want to add those system keyspaces. And that's fine because we exclude the system keyspace in the `keyspace_is_allowed_to_restore()` function.

Yet I'm wondering if restoring other system keyspaces is ok with the sstable loader (ie `system_distributed` and `system_schema`. 

@adejanovski do you think restoring those 2 tables in the case we use a sstableloader is a problem, or not?

**Comment by adejanovski-ds** [comment]
With the sstableloader, we should not restore the `system_schema` keyspace as the schema gets recreated using the backed up `schema.cql` file.

**Comment by adejanovski** [comment]
@arodrime, with the sstableloader, we should not restore the system_schema keyspace as the schema gets recreated using the backed up schema.cql file.

**Comment by arodrime** [comment]
After talking with Alex, I need to make a quick fix here still. Will do tomorrow.

**Comment by arodrime** [comment]
@adejanovski
- tests are passing now ¯\_(ツ)_/¯
- manual testing make me confident as well

It should be easy enough to review quickly if you could. Then happy to merge on my side.

**Pull request merged**
