### PR TITLE
Use multi-stage building in the Dockerfile to reduce image size

### PR DESCRIPTION
**Pull request by burmanm**
New:

```
REPOSITORY                                 TAG        IMAGE ID       CREATED             SIZE
<none>                                     <none>     e8830ab83fb8   13 minutes ago      372MB
```

Old:

```
<none>                                     <none>     712150e5744f   4 hours ago         2.04GB
```

Will require some real testing to ensure all the features work.

Intended to fix https://github.com/k8ssandra/k8ssandra/issues/191

### CODE REVIEW

**Comment by jsanda** [comment]
Do you think it would be worth trying to use something like a distroless base image?

**Comment by burmanm** [comment]
You mean Python base image? Well, it might reduce a bit (but requires rewriting the .sh scripts at least with Python), but I'm not sure if that's more than maybe ~50MB.

**Comment by burmanm** [comment]
That is, the base image (Ubuntu 18.04) is 64MB, Python dependencies are 225MB, python3+wget is 73MB. So some reductions are possible from the base+Python3 installation, but I doubt that's a lot. The Python dependencies are majority.

**Review by jsanda — CHANGES_REQUESTED** [review]
I tested the image in k8ssandra and the `medusa` container which runs the gRPC service fails at startup:

```
[2021-01-25 00:54:32,140] INFO: Init service
DEBUG:root:Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials
[2021-01-25 00:54:32,140] DEBUG: Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/medusa/service/grpc/server.py", line 139, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/app/medusa/service/grpc/server.py", line 30, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/app/medusa/storage/__init__.py", line 65, in __init__
    self.storage_driver = self._connect_storage()
  File "/app/medusa/storage/__init__.py", line 76, in _connect_storage
    s3_storage = S3Storage(self._config)
  File "/app/medusa/storage/abstract_storage.py", line 39, in __init__
    self.driver = self.connect_storage()
  File "/app/medusa/storage/s3_storage.py", line 135, in connect_storage
    self.set_upload_bandwidth()
  File "/app/medusa/storage/s3_storage.py", line 256, in set_upload_bandwidth
    self.config.transfer_max_bandwidth,
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'aws': 'aws'
```

**Comment by burmanm** [comment]
I think that issue is related to some other change in medusa versions.

**Comment by adejanovski** [comment]
Without digging too much, maybe [this is](https://github.com/thelastpickle/cassandra-medusa/pull/257/files#diff-463c905664353b772f4224283119f07d244c811b8b411ff90cd9610a59b67a6bR43) what caused it? 

Apparently the aws cli binary cannot be found in the path anymore.
If you know where it gets installed specfically in the container then you should maybe add it to the above line so we can be sure Medusa will find it.

**Comment by burmanm** [comment]
Considering the path was previously: ``ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin`` there was no change to the awscli's location. Hmm.

**Comment by burmanm** [comment]
Ah, now I get it. So while requirements-s3.txt does define the pip install to install awscli, that file isn't copied (and never was) to actual Dockerfile. It worked previously because awscli was installed by apt-get and that requirements-s3.txt wasn't used. Was there a reason these are all separate files?

**Comment by adejanovski** [comment]
Yes because we don't want all cloud vendor dependencies to be installed in all cases. We could end up with a fairly big list eventually.
When using pip to install medusa, folks can use `pip install cassandra-medusa[S3]` or `pip install cassandra-medusa[GCS]` for example, depending whether the backups are to be stored in S3 or GCS.

**Comment by burmanm** [comment]
It was always installed in the previous Kubernetes-image. So should we copy all the requirements.txts for the k8s Dockerfile?

**Comment by adejanovski** [comment]
Well, unless we want to have one Dockerfile per storage backend, I guess we have to copy them all indeed.

**Comment by jsanda** [comment]
>Yes because we don't want all cloud vendor dependencies to be installed in all cases. We could end up with a fairly big list eventually.

Agreed

>It was always installed in the previous Kubernetes-image. So should we copy all the requirements.txts for the k8s Dockerfile?

@burmanm I am inclined to say no provided it is not a lot of additional effort. To support this in k8ssandra we would need to introduce some logic to pick the right image. That could be based off of the supported values of the `storage_provider` property in `medusa.ini`.

**Review by jsanda — CHANGES_REQUESTED** [review]
It still fails after the latest changes. Here is the logs from my test:

```
[2021-01-26 05:07:24,987] DEBUG: https://s3.amazonaws.com:443 "HEAD /k8ssandra-medusa-dev HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/app/medusa/storage/s3_storage.py", line 146, in check_dependencies
    subprocess.check_call([aws_cli_path, "help"], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['aws', 'help']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/medusa/service/grpc/server.py", line 139, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/app/medusa/service/grpc/server.py", line 30, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/app/medusa/storage/__init__.py", line 65, in __init__
    self.storage_driver = self._connect_storage()
  File "/app/medusa/storage/__init__.py", line 77, in _connect_storage
    s3_storage.check_dependencies()
  File "/app/medusa/storage/s3_storage.py", line 151, in check_dependencies
    + "or 'sudo apt-get install awscli' and try again."
RuntimeError: AWS cli doesn't seem to be installed on this system and is a required dependency for the S3 backend. Please install it by running 'pip install awscli' or 'sudo apt-get install awscli' and try again.
```

**Comment by adejanovski** [comment]
I think it's because `pip` and `apt` won't install the `aws` cli binary in the same location as reported in #78.
You could set the `aws_cli_path` config setting to `dynamic` which would allow Medusa to look for it in the different locations it should be: https://github.com/thelastpickle/cassandra-medusa/pull/77/files#diff-099702fa41ee65b22cbe8672b0b38bbe45caed3906870b29e71ca782e5df7fc1R41

Or find where it gets installed in the container and add that location to PATH.

**Comment by burmanm** [comment]
Per my inspection it's in /root/.local/bin, which is also set in the PATH.

**Comment by burmanm** [comment]
```
⋊> ~/bin docker run -it --entrypoint /bin/bash 83371e6ac8e2                                                                                                                    09:44:07
root@d9b46a46ca37:/app# aws
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command
root@d9b46a46ca37:/app#
```

**Comment by burmanm** [comment]
Ah, the issue comes from the Medusa's use of "aws help". Now, that command requires some additional 160MB of dependencies to display the help command - but those dependencies are not otherwise needed.

**Comment by adejanovski** [comment]
@burmanm, we should rather switch to another command to test the presence of the aws cli dependency. Maybe just running `aws` should be enough. wdyt?

**Review by jsanda — CHANGES_REQUESTED** [review]
Still failing:

```
Traceback (most recent call last):
  File "/app/medusa/storage/s3_storage.py", line 146, in check_dependencies
    subprocess.check_call([aws_cli_path], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['aws']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/medusa/service/grpc/server.py", line 154, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/app/medusa/service/grpc/server.py", line 45, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/app/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/app/medusa/storage/__init__.py", line 88, in _connect_storage
    s3_storage.check_dependencies()
  File "/app/medusa/storage/s3_storage.py", line 151, in check_dependencies
    + "or 'sudo apt-get install awscli' and try again."
RuntimeError: AWS cli doesn't seem to be installed on this system and is a required dependency for the S3 backend. Please install it by running 'pip install awscli' or 'sudo apt-get install awscli' and try again.
```

**Comment by jsanda** [comment]
I tested this again just now because I thought I may have built the image incorrectly yesterday. I still get the same error that reported previously.

**Comment by burmanm** [comment]
That's actually correct error code it seems.. well, so just running 'aws' won't work.

**Review by adejanovski — APPROVED** [review]
Successfully tested the image @burmanm 👍 

Comparing 0.8.1:
k8ssandra-medusa-Tags-Docker-Hub

To this one:
adejanovski-cassandra-medusa-Tags-Docker-Hub

Pretty great size reduction! 😅

**Comment by jsanda** [comment]
I tested in k8ssandra and this looks good. Nice work!

**Review by jsanda — DISMISSED** [review]

**Comment by burmanm** [comment]
The latest commit updates the pip before installing the updated dependencies - otherwise the installation fails to missing setuptools_rust. Changes the running user to ``medusa`` instead of ``root``.

@jsanda Fixes #279 

```
⋊> ~/p/g/d/k8ssandra on add_s3_options ⨯ kubectl exec -it k8ssandra-dc1-default-sts-0 -c medusa -- /bin/sh                                                                                                                                                                                  16:31:30
$ ps xa
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /bin/bash /home/medusa/app/docker-entrypoint.sh
      8 ?        Sl     0:00 python3 -m medusa.service.grpc.server server.py
   1105 pts/0    Ss     0:00 /bin/sh
   1112 pts/0    R+     0:00 ps xa
$ whoami
medusa
$
```

**Review by jsanda — APPROVED** [review]
Thanks for this!

**Pull request merged**
