### PR TITLE
Add support for IBM Cloud object storage

### PR DESCRIPTION
**Pull request by adejanovski**

### CODE REVIEW

**Comment by arodrime** [comment]
@adejanovski:
* "This branch is out-of-date with the base branch"
*  S3 test with 2.2.14 seem to fail for some reason :(.
* I don't see IBM cloud storage tests being run either? 🤔 

Looking at the code now.

**Comment by arodrime** [comment]
The code is looking good. Not much code deletion, thus it's quite safe.
Plus all the IBM cloud storage code here is similar to AWS one and was duly tested. I'm ok with merging this.

@adejanovski it would be great to ask IBM folks if they would provide us with credentials for medusa testing purposes that don't have us hitting the API limits, so we ensure that IBM tests are running as well (no regression, IBM working with future releases automatically tested...)

**Review by arodrime — DISMISSED** [review]

**Comment by robbybb** [comment]
The code looks good to me.  I have no comments.

**Comment by arodrime** [comment]
Rebased after merging CI fixes (your sstableloader fix on master for C*4.0).

**Review by arodrime — APPROVED** [review]
Looks good to me @adejanovski. I'll rebase one more time, but tests passed at the time of writing.

**Review by arodrime — APPROVED** [review]

**Pull request merged**
