### PR TITLE
Update TLS version

### PR DESCRIPTION
**Pull request by mkcello96**
Continues the work started here: https://github.com/thelastpickle/cassandra-medusa/pull/177. 

I followed @arodrime's advice in his comment from the above PR ([link to that comment](https://github.com/thelastpickle/cassandra-medusa/pull/177#issuecomment-664297068))

### CODE REVIEW

**Comment by mkcello96** [comment]
`TLS_PROTOCAL` is new in Python 3.6 - that would be my best guess as to why some of the debian-builds are failing. Please let me know if you have more insight.

**Comment by mkcello96** [comment]
@arodrime Would you please review this PR and let me know what your preferred approach is to the old debian xenial build is? Thank you!

**Comment by adejanovski** [comment]
@mkcello96, 

following up on the ASF slack convo, would you mind switching the build image for the stretch/xenial packages to `python:3.6.12-stretch`? 

I guess (and hope) that should do the trick.
And yes, we dropped support for Python 3.5 officially, but it would still be good to support Xenial and Stretch.

I'll take a pass on the PR ASAP, thanks for sending it!

**Comment by mkcello96** [comment]
@adejanovski Doesn't look like that worked :( 
`Error: no packages found for xenial`

**Comment by adejanovski** [comment]
@mkcello96, I'm giving up on Xenial and Stretch. Can't get them to build debian packages properly using python 3.6.
Let's remove them from the built packages as you suggested and move forward with this PR.

**Comment by mkcello96** [comment]
Thanks again for your time and effort @adejanovski! I updated as recommended.

FYI same issue with the `Build, test and Release / build (3.8) (pull_request)` seems to be happening on the last PR as well (just in case there are concerns that the build changes here caused it). https://github.com/thelastpickle/cassandra-medusa/runs/1784430396

**Comment by adejanovski** [comment]
@mkcello96, I ran the full integration test suite on #269 and it's all green 👍 
Could you please squash all your commits in this PR and then I'll merge it.

Thanks!

**Comment by mkcello96** [comment]
@adejanovski Thanks!! 

I squashed the commits in this PR and ended up in a slightly weird state since I had merged master a few times (but didn't seem completely up to date).
In case you want to use a cleaner version, here's a branch from my forked repo that doesn't replay any later commits: https://github.com/mkcello96/cassandra-medusa/tree/update-tls-saved

**Comment by adejanovski** [comment]
yeah, we have some squashed changes here that don't belong to this PR.
I'll handle this and let you know when it's merged, no worries.

Quick tip if I may: never merge master into a feature branch, always rebase your branch on top of master to get it up to date ;)

**Comment by mkcello96** [comment]
@adejanovski Thank you, that makes a lot of sense :). Not used to developing on forks yet.
The other branch I linked doesn't have any merges from master in it, should be cleaner. Thanks for handling the merge!

**Comment by adejanovski** [comment]
Merged in #277, thanks @mkcello96 !

**Comment by arodrime** [comment]
@adejanovski thanks for handling this. @mkcello96 I was out for a couple of month. Thanks for resuming and wrapping up that work!

**Pull request closed without merging**
