### PR TITLE
Use streams for uploading and downloading

### PR DESCRIPTION
**Pull request by nicholasamorim**
Related to #58.

Changes uploading and downloading to use the stream methods `upload_object_via_stream` and `object.as_stream()`

### CODE REVIEW

**Comment by nicholasamorim** [comment]
I'll fix the tests as soon as I can. But I'm trying to understand this:

image

What's the correct expectation in there?

1) Did the previous function `download()` automatically appended the filename?
2) Or is this just a question of mocking the `open` anyways?

**Comment by adejanovski** [comment]
Hi @nicholasamorim,

`blob.download()` automatically appends the file name indeed, although it can also take the full path with the filename in the destination arg.
You should try to build the destination path as done here : https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/aws_s3_storage/concurrent.py#L196-L203

**Comment by adejanovski** [comment]
Hi @nicholasamorim,

were you able to make some progress on this PR? Anything you need help with?

**Comment by nicholasamorim** [comment]
Just haven't had the time to fix the code and test. Will do it this week

**Comment by adejanovski** [comment]
Hi @nicholasamorim,

I can finish the work on this PR if you want me to and don't have time to deal with it. Just let me know.

Cheers

**Comment by nicholasamorim** [comment]
Hey @adejanovski, that would be great. I'm swamped indeed.

**Pull request merged**
