### PR TITLE
Allow awscli use on venvs

### PR DESCRIPTION
**Pull request by bishoprunout**
Dynamically find awscli binary 
This more so  a example for issue  https://github.com/thelastpickle/cassandra-medusa/issues/78

### CODE REVIEW

**Comment by bishoprunout** [comment]
@adejanovski  That sounds good to me. I figured config option  will be likely required for this. I'll try get back this when I have time. Thanks for the reply

**Comment by bishoprunout** [comment]
@adejanovski  this should be good to go now

**Comment by adejanovski** [comment]
Hi @bishoprunout, 

I'll run some tests on your work to check that it's behaving as expected.
Once I'm happy with it, you'll have to deal with some merge conflicts with `master`. Could you please rebase your branch on top of the current `master` upstream branch, then squash your commits into a single one?

Much appreciated!

**Comment by bishoprunout** [comment]
@adejanovski  done I think

**Comment by adejanovski** [comment]
Hi @bishoprunout,

sadly it's not ok yet.
You still have 12 commits in there:
Allow awscli use on venvs by bishoprunout · Pull Request  77 · thelastpickle cassandra-medusa

And the branch still has conflicts with master:
Allow awscli use on venvs by bishoprunout · Pull Request  77 · thelastpickle cassandra-medusa (1)

Here's what you should do:
- Squash your commits into a single one as shown here : https://stackoverflow.com/a/43246375/5106246
- Refresh your fork master branch and rebase your master branch on the upstream one: 
```
git checkout master
git fetch upstream
git rebase upstream/master
git checkout patch-1
git rebase master
```
- At this point, you'll have some conflicts to fix.
- Force push your branch: `git push --force-with-lease`

Let me know if you need more help.

**Comment by bishoprunout** [comment]
@adejanovski  okay Its done for real now

**Comment by adejanovski** [comment]
Yeah :D 

Well, I'm running some tests and ran into an issue: 

```
$ medusa backup --backup-name=backup_three
[2020-03-04 13:26:50,890] INFO: Monitoring provider is noop
[2020-03-04 13:26:50,940] ERROR: This error happened during the backup: AWS cli doesn't seem to be installed on this system and is a required dependency for the S3 backend. Please install it by running 'pip install awscli' or 'sudo apt-get install awscli' and try again.
Traceback (most recent call last):
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/medusa/storage/s3_storage.py", line 141, in check_dependencies
    subprocess.check_call([aws_cli_path, "help"], stdout=PIPE, stderr=PIPE)
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/gevent/subprocess.py", line 270, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/gevent/subprocess.py", line 249, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/gevent/subprocess.py", line 627, in __init__
    restore_signals, start_new_session)
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/gevent/subprocess.py", line 1505, in _execute_child
    raise child_exception
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/aws'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/medusa/backup.py", line 227, in main
    storage = Storage(config=config.storage)
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/medusa/storage/__init__.py", line 59, in __init__
    self.storage_driver = self._connect_storage()
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/medusa/storage/__init__.py", line 71, in _connect_storage
    s3_storage.check_dependencies()
  File "/usr/share/cassandra-medusa/lib/python3.6/site-packages/medusa/storage/s3_storage.py", line 146, in check_dependencies
    + "or 'sudo apt-get install awscli' and try again."
RuntimeError: AWS cli doesn't seem to be installed on this system and is a required dependency for the S3 backend. Please install it by running 'pip install awscli' or 'sudo apt-get install awscli' and try again.
ubuntu@ip-172-31-34-44:/etc/medusa$ which aws
/usr/local/bin/aws
```

I installed `awscli` using `pip`, which puts the `aws` binary under `/usr/local/bin`.
If I install it with `apt-get`, it goes under `/usr/bin` as you seem to expect it.
My recommendation here would be:
Instead of cycling through the entries of `sys.path`, you should create a list that concatenates `sys.path`, `/usr/bin/` and `/usr/local/bin`, and loop over it [here](https://github.com/thelastpickle/cassandra-medusa/pull/77/files#diff-8e3f53e92269b2855aa9d36d6c6d579bR60).

If the aws binary can't be found in any of these directories, you should fallback to just `aws`, which will trigger the default behavior. The dependency will be checked for presence, and if it can't be found, an exception will be raised.

What do you think?
The rest looks good to me.

**Comment by bishoprunout** [comment]
@adejanovski  done

**Pull request merged**
