### PR TITLE
Swap to cassandra user to avoid chown issues

### PR DESCRIPTION
**Pull request by burmanm**

### CODE REVIEW

**Comment by burmanm** [comment]
```
➜  cassandra-medusa git:(change_to_cassandra_user) ✗ docker run -i -t --entrypoint /bin/bash 1fb9e1dcfa21
cassandra@8c010c07ddbe:~$ whoami
cassandra
cassandra@8c010c07ddbe:~$ id
uid=999(cassandra) gid=999(cassandra) groups=999(cassandra)
cassandra@8c010c07ddbe:~$ pwd
/home/cassandra
cassandra@8c010c07ddbe:~$ ls -la
total 36
drwxr-xr-x 1 cassandra cassandra 4096 Feb 18 05:49 .
drwxr-xr-x 1 root      root      4096 Feb 18 05:47 ..
-rw-r--r-- 1 cassandra cassandra  220 Apr  4  2018 .bash_logout
-rw-r--r-- 1 cassandra cassandra 3771 Apr  4  2018 .bashrc
drwxr-xr-x 5 cassandra cassandra 4096 Feb 18 05:49 .local
-rw-r--r-- 1 cassandra cassandra  807 Apr  4  2018 .profile
-rwxr-xr-x 1 cassandra cassandra 1933 Jan 27 06:05 docker-entrypoint.sh
drwxr-xr-x 7 cassandra cassandra 4096 Feb 18 05:49 medusa
cassandra@8c010c07ddbe:~$ exit
```

**Review by jsanda — COMMENTED** [review]
Tested in k8ssandra and get a permission error:

```
[Errno 13] Permission denied: '/home/cassandra'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/install/medusa/service/grpc/server.py", line 158, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/install/medusa/service/grpc/server.py", line 45, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/install/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/install/medusa/storage/__init__.py", line 95, in _connect_storage
    s3_storage = S3Storage(self._config)
  File "/install/medusa/storage/abstract_storage.py", line 39, in __init__
    self.driver = self.connect_storage()
  File "/install/medusa/storage/s3_storage.py", line 103, in connect_storage
    self.set_upload_bandwidth()
  File "/install/medusa/storage/s3_base_storage.py", line 196, in set_upload_bandwidth
    self.config.transfer_max_bandwidth,
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['aws', 'configure', 'set', 'default.s3.max_bandwidth', '50MB/s']' returned non-zero exit status 255.
```

**Comment by jsanda** [comment]
My previous error may be due to a missing group id in the SecurityContext I am using in k8ssandra. I am testing again with the group id added back.

**Comment by jsanda** [comment]
I fixed my k8s security context and tested backup/restore in k8ssandra with an S3 bucket. Everything looks good! 

I will do another test with a GCS bucket.

**Comment by burmanm** [comment]
I returned the google-cloud-sdk for now and created a ticket #288 to make this process more sane. Now, even with the small cleanup it still adds 303MB to the Dockerfile, but without cleaning it would add over 900MB. The cloud-sdk is really not a good way to run these Python tools.

**Comment by jsanda** [comment]
Thanks for the google-cloud-sdk changes. I did a backup/restore with GCS in k8ssandra to verify things are good.

**Review by jsanda — DISMISSED** [review]

**Review by jsanda — APPROVED** [review]

**Pull request merged**
