### PR TITLE
feat(iam): support assume role

### PR DESCRIPTION
**Pull request by JBOClara**
Fix https://github.com/thelastpickle/cassandra-medusa/pull/691

### CODE REVIEW

**Review by adejanovski — CHANGES_REQUESTED** [review]
Hi @JBOClara, 

a few things here:
- There's a lot of noise in this PR due to reformatting of unmodified code, most probably due to your IDE settings. Could you revert these changes so that it's clear what was modified by this PR specifically?
- This [comment](https://github.com/thelastpickle/cassandra-medusa/issues/692#issuecomment-1838445336) suggests that there's a simpler solution which would be to construct the client without passing credentials if none are provided. That seems like an interesting option but is not what's done in your PR. What's your opinion on this?

**Comment by azman0101** [comment]
> Hi @JBOClara,
> 
> a few things here:
> 
> * There's a lot of noise in this PR due to reformatting of unmodified code, most probably due to your IDE settings. Could you revert these changes so that it's clear what was modified by this PR specifically?
> * This [comment](https://github.com/thelastpickle/cassandra-medusa/issues/692#issuecomment-1838445336) suggests that there's a simpler solution which would be to construct the client without passing credentials if none are provided. That seems like an interesting option but is not what's done in your PR. What's your opinion on this?

Ok, I'll review the formatting.

About the simpler solution, I'm currently implementing it.

I have a hard time mocking the token file `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` to cover my new code.

**Comment by adejanovski** [comment]
> > Hi @JBOClara,
> > a few things here:
> > 
> > * There's a lot of noise in this PR due to reformatting of unmodified code, most probably due to your IDE settings. Could you revert these changes so that it's clear what was modified by this PR specifically?
> > * This [comment](https://github.com/thelastpickle/cassandra-medusa/issues/692#issuecomment-1838445336) suggests that there's a simpler solution which would be to construct the client without passing credentials if none are provided. That seems like an interesting option but is not what's done in your PR. What's your opinion on this?
> 
> Ok, I'll review the formatting.
> 
> About the simpler solution, I'm currently implementing it.
> 
> I have a hard time mocking the token file `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` to cover my new code.

I'm confused, you're using two separate github accounts, right? 🙂 
Let me know if we can help with your current mocking issues to get this moving forward.

**Comment by JBOClara** [comment]
> I'm confused, you're using two separate github accounts, right? 🙂 
> Let me know if we can help with your current mocking issues to get this moving forward.

Sorry for the confusion, I'll make sure not to make the mistake again.

I will push my changes to discuss this topic.

**Comment by adejanovski** [comment]
> Sorry for the confusion, I'll make sure not to make the mistake again.
> 
> I will push my changes to discuss this topic.

No worries, thanks!

**Review by adejanovski — CHANGES_REQUESTED** [review]
Changes look good and I was able to successfully test them using a role attached to an ec2 instance 👍 

**Issue:** CI is failing due to formatting issues detected by flake8. See [here](https://github.com/thelastpickle/cassandra-medusa/actions/runs/7278646587/job/19833299406?pr=691#step:6:28).
Once these are fixed and CI passes, we'll be good for a merge.
Thanks!

**Review by adejanovski — APPROVED** [review]
Awesome stuff, thanks @JBOClara 🙏

**Pull request merged**
